import { SyncedClock } from '../components/SyncedClock'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { useStudy } from '../hooks/useStudy'
import { client } from '../lib/supabase'
import { loadOwned } from '../lib/loadOwned'
import { friendlyError } from '../lib/errors'
import { duration, weeklyMinutes, type StudySession } from '../lib/focus'
import { localDate, displayDate } from '../types/study'
import { weekRange } from '../lib/calendar'
import { Field, Notice, Submit, Loading } from '../components/UI'
import { Pagination, usePagination } from '../components/Pagination'
export default function Focus() {
 const {session}=useAuth();const owner=session!.user.id;const study=useStudy();const today=localDate()
 const [rows,setRows]=useState<StudySession[]>([]);const [goal,setGoal]=useState(0);const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0)
 const [loadError,setLoadError]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false)
 const [editing,setEditing]=useState<StudySession|null>(null)
 const [minutes,setMinutes]=useState('25');const [deleting,setDeleting]=useState<StudySession|null>(null);const requestId=useRef(crypto.randomUUID());const formRef=useRef<HTMLFormElement>(null)
 const [filter,setFilter]=useState('all');const filtered=rows.filter(s=>filter==='all'||s.course_id===filter);const pagination=usePagination(filtered,filter)
 useEffect(()=>{const controller=new AbortController();let active=true;setLoading(true);setLoadError('');Promise.all([loadOwned<StudySession>('study_sessions',owner,controller.signal),client().from('study_goals').select('weekly_minutes').eq('user_id',owner).abortSignal(controller.signal).maybeSingle()]).then(([sessions,g])=>{if(!active)return;if(g.error)throw g.error;setRows(sessions.sort((a,b)=>b.studied_on.localeCompare(a.studied_on)||b.created_at.localeCompare(a.created_at)));setGoal(g.data?.weekly_minutes??0)}).catch(e=>{if(active)setLoadError(friendlyError(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;controller.abort()}},[owner,revision])
 async function saveGoal(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const value=Number(new FormData(event.currentTarget).get('goal'));setBusy(true);setError('');setSuccess('');try{const {error}=await client().from('study_goals').upsert({user_id:owner,weekly_minutes:Math.round(value*60)},{onConflict:'user_id'}).select().single();if(error)throw error;setGoal(Math.round(value*60));setSuccess('Meta semanal salva.')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 async function saveSession(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=new FormData(event.currentTarget);const count=Number(minutes);const date=String(form.get('date'));if(!Number.isInteger(count)||count<1||count>720||date>today){setError('Informe de 1 a 720 minutos e uma data até hoje.');return}setBusy(true);setError('');setSuccess('');const values={id:requestId.current,user_id:owner,course_id:String(form.get('course'))||null,studied_on:date,minutes:count,note:String(form.get('note')).trim()};try{const request=editing?client().from('study_sessions').update({course_id:values.course_id,studied_on:values.studied_on,minutes:values.minutes,note:values.note}).eq('id',editing.id).eq('user_id',owner):client().from('study_sessions').insert(values);const {error}=await request.select('id').single();if(error){if(editing||error.code!=='23505')throw error;const existing=await client().from('study_sessions').select('*').eq('id',requestId.current).eq('user_id',owner).single();if(existing.error)throw existing.error;setSuccess('A sessão já havia sido salva. O histórico foi atualizado.');}requestId.current=crypto.randomUUID();formRef.current?.reset();setMinutes('25');setSuccess(editing?'Sessão atualizada.':'Sessão registrada.');setEditing(null);setRevision(n=>n+1)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 async function remove(){if(!deleting||busy)return;setBusy(true);setError('');setSuccess('');try{const {error}=await client().from('study_sessions').delete().eq('id',deleting.id).eq('user_id',owner).select('id').single();if(error)throw error;setDeleting(null);setSuccess('Sessão excluída.');setRevision(n=>n+1)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const total=weeklyMinutes(rows,today);const range=weekRange(today)
 return <section className="study"><span className="eyebrow">UM PASSO DE CADA VEZ</span><h1>Meu ritmo</h1><p>Registre seu tempo de estudo e acompanhe uma meta que faça sentido para você.</p><Notice error>{error||loadError||study.error}</Notice><Notice>{success}</Notice>{(loadError||study.error)&&<button className="secondary" onClick={()=>{setRevision(n=>n+1);study.reload()}}>Tentar novamente</button>}
 <SyncedClock courses={study.courses} onSaved={()=>setRevision(n=>n+1)}/>
 {loading||study.loading?<Loading/>:!loadError&&!study.error&&<><section><h2>Esta semana · {displayDate(range.start)} a {displayDate(range.end)}</h2><p><strong>{duration(total)}</strong> registradas{goal>0?` de ${duration(goal)} planejadas`:''}.</p>{goal>0&&<progress className="weekly-progress" max={goal} value={Math.min(total,goal)} aria-label="Progresso da meta semanal"/>}<form onSubmit={saveGoal} className="goal-form" key={goal}><fieldset disabled={busy}><Field label="Meta semanal (horas)" name="goal" type="number" min={0} max={168} step="0.5" defaultValue={goal/60} required/><p>Use zero para ficar sem meta. A meta se repete a cada semana.</p><Submit busy={busy}>Salvar meta</Submit></fieldset></form></section>
 <form key={editing?.id??'new'} ref={formRef} onSubmit={saveSession} className="study-form"><h2>{editing?'Editar sessão':'Registrar sessão manual'}</h2><fieldset disabled={busy}><div className="form-grid"><Field label="Data do estudo" name="date" type="date" defaultValue={editing?.studied_on??today} max={today} required/><Field label="Tempo (minutos completos)" type="number" min={1} max={720} step={1} value={minutes} onChange={e=>setMinutes(e.target.value)} required/></div><label className="field">Curso (opcional)<select name="course" defaultValue={editing?.course_id??''}><option value="">Sem curso</option>{study.courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><Field label="O que você estudou? (opcional)" name="note" defaultValue={editing?.note??''} maxLength={500}/><Submit busy={busy}>Salvar sessão</Submit>{editing&&<button className="secondary" type="button" onClick={()=>{setEditing(null);setMinutes('25')}}>Cancelar edição</button>}</fieldset></form>
 <h2>Últimas quatro semanas</h2><ul className="deadline-list">{[0,1,2,3].map(offset=>{const day=new Date(`${today}T12:00:00`);day.setDate(day.getDate()-offset*7);const date=localDate(day);return <li key={date}><span>Semana de {displayDate(weekRange(date).start)}</span><strong>{duration(weeklyMinutes(rows,date))}</strong></li>})}</ul>
 <h2>Histórico</h2><label className="field">Filtrar sessões por curso<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{study.courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{deleting&&<div className="delete-confirm" role="alert"><p>Excluir a sessão de {displayDate(deleting.studied_on)}? O tempo será retirado das estatísticas.</p><div className="actions"><button className="secondary danger" disabled={busy} onClick={remove}>Confirmar exclusão</button><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>Cancelar</button></div></div>}{filtered.length?<ul className="study-list">{pagination.items.map(s=><li key={s.id}><div className="record-main"><div><h3>{displayDate(s.studied_on)} · {duration(s.minutes)}</h3><p>{study.courses.find(c=>c.id===s.course_id)?.title??'Sem curso'}{s.note?` · ${s.note}`:''}</p></div></div><button className="text-button" disabled={busy} onClick={()=>{setEditing(s);setMinutes(String(s.minutes));setError('');setSuccess('');setDeleting(null)}}>Editar</button><button className="text-button danger" disabled={busy} aria-label={`Excluir sessão de ${displayDate(s.studied_on)}`} onClick={()=>setDeleting(s)}>Excluir</button></li>)}</ul>:<p>Nenhuma sessão registrada nesta visualização.</p>}<Pagination {...pagination}/></>}
 </section>
}
