import { useState } from 'react'
import { client } from '../lib/supabase'
import { Notice } from './UI'
interface UnusedFile { bucket_id:string;path:string;created_at:string }
export function StorageCleanup() {
 const [files,setFiles]=useState<UnusedFile[]|null>(null);const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const id=(file:UnusedFile)=>`${file.bucket_id}:${file.path}`
 async function scan(){setBusy(true);setError('');setSuccess('');setConfirm(false);try{const {data,error}=await client().rpc('list_unused_files');if(error)throw error;setFiles(data);setSelected([])}catch{setError('Não foi possível verificar os arquivos. Tente novamente.')}finally{setBusy(false)}}
 async function remove(){if(busy)return;setBusy(true);setError('');let removed=0;let failed=0;const completed:string[]=[];try{for(const file of files??[]){if(!selected.includes(id(file)))continue;try{const claim=await client().rpc('claim_unused_file',{p_bucket:file.bucket_id,p_path:file.path});if(claim.error||!claim.data){failed++;continue}const result=await client().storage.from(file.bucket_id).remove([file.path]);if(result.error||!result.data?.length){failed++;continue}removed++;completed.push(id(file))}catch{failed++}}setFiles(current=>current?.filter(file=>!completed.includes(id(file)))??null);setSelected([]);setConfirm(false);setSuccess(`${removed} arquivo(s) removido(s).`);if(failed)setError(`${failed} arquivo(s) não foram removidos: podem estar em uso ou a conexão falhou. Verifique novamente.`)}finally{setBusy(false)}}
 return <section className="storage-cleanup"><h2>Limpar arquivos sem uso</h2><p>Encontre fotos e certificados sem vínculo, enviados há mais de 24 horas. Confira antes de remover: a exclusão é permanente.</p><Notice error>{error}</Notice><Notice>{success}</Notice><button className="secondary" disabled={busy} onClick={scan}>{busy?'Processando…':'Verificar arquivos'}</button>{files&&<><p>{files.length?`Até 100 arquivos por verificação · ${files.length} encontrado(s).`:'Nenhum arquivo sem uso encontrado.'}</p><ul className="cleanup-list">{files.map(file=><li key={id(file)}><label className="check-label"><input type="checkbox" disabled={busy} checked={selected.includes(id(file))} onChange={e=>setSelected(current=>e.target.checked?[...current,id(file)]:current.filter(key=>key!==id(file)))}/><span>{file.bucket_id==='avatars'?'Foto':'Certificado'} · {file.path.split('/').pop()} · {new Date(file.created_at).toLocaleDateString('pt-BR')}</span></label></li>)}</ul>{selected.length>0&&!confirm&&<button className="secondary danger" disabled={busy} onClick={()=>setConfirm(true)}>Remover selecionados ({selected.length})</button>}{confirm&&<div className="delete-confirm" role="alert"><p>Excluir permanentemente {selected.length} arquivo(s) selecionado(s)?</p><div className="actions"><button className="secondary danger" disabled={busy} onClick={remove}>Confirmar exclusão dos arquivos</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>Cancelar</button></div></div>}</>}</section>
}
