import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { client } from '../lib/supabase'
import { elapsedSeconds } from '../lib/focus'
import { localDate, type Course } from '../types/study'
import { Field, Loading, Notice, Submit } from './UI'
interface Clock { accumulated:number;started_at:string|null;version:number;run_id:string;server_now:string }
export function SyncedClock({courses,onSaved}:{courses:Course[];onSaved:()=>void}) {
 const [clock,setClock]=useState<Clock|null>(null);const [now,setNow]=useState(Date.now());const offset=useRef(0)
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [confirm,setConfirm]=useState(false)
 const inFlight=useRef(false);const alive=useRef(true)
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;try{const {data,error}=await client().rpc('study_clock_command',{p_action:'read'});if(error)throw error;if(alive.current){offset.current=Date.parse(data.server_now)-Date.now();setClock(data);setNow(Date.now());setError('')}}catch{if(alive.current)setError('Não foi possível sincronizar o cronômetro. Verifique sua conexão.')}finally{inFlight.current=false}},[])
 useEffect(()=>{alive.current=true;void refresh();const poll=setInterval(()=>void refresh(),10000);const tick=setInterval(()=>setNow(Date.now()),1000);const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{alive.current=false;clearInterval(poll);clearInterval(tick);window.removeEventListener('focus',focus)}},[refresh])
 async function command(action:string,fields:Record<string,unknown>={}) {if(!clock||inFlight.current)return false;inFlight.current=true;setBusy(true);setError('');setSuccess('');let ok=false;try{const {data,error}=await client().rpc('study_clock_command',{p_action:action,p_version:clock.version,p_run_id:clock.run_id,...fields});if(error)throw error;if(alive.current){offset.current=Date.parse(data.server_now)-Date.now();setClock(data);setNow(Date.now());setConfirm(false);setSuccess(action==='finish'?'Sessão salva e cronômetro reiniciado.':'Cronômetro sincronizado.')}ok=true}catch(e){if(alive.current)setError(typeof e==='object'&&e!==null&&'message' in e&&String(e.message).includes('clock_conflict')?'O cronômetro foi alterado em outro dispositivo. Atualize antes de continuar.':'Não foi possível confirmar a operação. Atualize antes de tentar novamente.')}finally{inFlight.current=false;if(alive.current)setBusy(false)}return ok}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(await command('finish',{p_date:form.get('date'),p_course:form.get('course')||null,p_note:String(form.get('note')).trim()}))onSaved()}
 const seconds=clock?elapsedSeconds(clock.accumulated,clock.started_at?Date.parse(clock.started_at):null,now+offset.current):0
 return <section className="focus-clock" aria-label="Cronômetro sincronizado"><h2>Tempo de estudo</h2><Notice error>{error}</Notice><Notice>{success}</Notice>{!clock&&!error?<Loading/>:<><output aria-label="Tempo decorrido">{String(Math.floor(seconds/3600)).padStart(2,'0')}:{String(Math.floor(seconds/60)%60).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</output><div className="actions"><button className="secondary" disabled={busy||!!error||!clock||(!clock.started_at&&seconds>=43200)} onClick={()=>void command(clock?.started_at?'pause':'start')}>{clock?.started_at?'Pausar':'Iniciar / continuar'}</button><button className="secondary" disabled={busy} onClick={()=>void refresh()}>Atualizar</button><button className="text-button" disabled={busy||!clock||!!error} onClick={()=>setConfirm(true)}>Zerar</button></div>{confirm&&<div className="delete-confirm"><p>Zerar o tempo ainda não salvo? As sessões do histórico serão mantidas.</p><button className="secondary danger" disabled={busy} onClick={()=>void command('reset')}>Confirmar reinício</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>Cancelar</button></div>}<p>Sincronizado com sua conta a cada 10 segundos e ao voltar à janela. Pause antes de registrar. Limite de 12 horas por sessão.</p>{clock&&!clock.started_at&&seconds>=60&&<form onSubmit={save} key={clock.run_id}><fieldset disabled={busy||!!error}><Field label="Data da sessão cronometrada" name="date" type="date" defaultValue={localDate()} max={localDate()} required/><label className="field">Curso da sessão cronometrada<select name="course"><option value="">Sem curso</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><Field label="Anotação da sessão cronometrada" name="note" maxLength={500}/><p>{Math.floor(seconds/60)} minutos completos serão registrados.</p><Submit busy={busy}>Salvar tempo cronometrado</Submit></fieldset></form>}</>}</section>
}
